import type { SpaceType } from "./types";

/**
 * Единый список конкретных Space Types (DS-7.2).
 *
 * Это конкретные помещения/объекты — на уровень детализации ниже Design
 * Domain (`src/lib/interior/design-domain`). Каждый элемент ссылается на
 * `DesignDomainId`, а не наоборот (Principle 21, ADR-000).
 *
 * Список сгруппирован по Design Domain только для читаемости — сама
 * группировка не является типом и не имеет структурного значения.
 * Список иллюстративный и намеренно неполный: добавление нового Space
 * Type — это просто новый элемент массива, без изменения формы
 * существующих (см. ./README.md, "Универсальность").
 */
export const SPACE_TYPES: SpaceType[] = [
  // Residential
  {
    id: "living_room",
    designDomainId: "residential",
    displayName: "Living Room",
    description: "Гостиная — основное пространство для отдыха и приёма гостей.",
    icon: "🛋️",
    metadata: { priority: 1, enabled: true },
  },
  {
    id: "bedroom",
    designDomainId: "residential",
    displayName: "Bedroom",
    description: "Спальня — пространство для сна и отдыха.",
    icon: "🛏️",
    metadata: { priority: 2, enabled: true },
  },
  {
    id: "kitchen",
    designDomainId: "residential",
    displayName: "Kitchen",
    description: "Кухня — пространство для приготовления пищи.",
    icon: "🍳",
    metadata: { priority: 3, enabled: true },
  },
  {
    id: "dining_room",
    designDomainId: "residential",
    displayName: "Dining Room",
    description: "Столовая — пространство для приёма пищи.",
    icon: "🍽️",
    metadata: { priority: 4, enabled: true },
  },
  {
    id: "bathroom",
    designDomainId: "residential",
    displayName: "Bathroom",
    description: "Ванная комната — пространство для гигиены.",
    icon: "🛁",
    metadata: { priority: 5, enabled: true },
  },
  {
    id: "home_office",
    designDomainId: "residential",
    displayName: "Home Office",
    description: "Домашний кабинет — пространство для работы дома.",
    icon: "💻",
    metadata: { priority: 6, enabled: true },
  },
  {
    id: "hallway",
    designDomainId: "residential",
    displayName: "Hallway",
    description: "Коридор/прихожая — соединительное пространство внутри жилья.",
    icon: "🚪",
    metadata: { priority: 7, enabled: true },
  },
  {
    id: "closet",
    designDomainId: "residential",
    displayName: "Closet",
    description: "Гардеробная/кладовая — пространство для хранения одежды и вещей.",
    icon: "🧥",
    metadata: { priority: 8, enabled: true },
  },
  {
    id: "laundry",
    designDomainId: "residential",
    displayName: "Laundry",
    description: "Постирочная — пространство для стирки и сушки белья.",
    icon: "🧺",
    metadata: { priority: 9, enabled: true },
  },
  {
    id: "balcony",
    designDomainId: "residential",
    displayName: "Balcony",
    description: "Балкон/лоджия — примыкающее к жилью открытое пространство.",
    icon: "🌇",
    metadata: { priority: 10, enabled: true },
  },
  {
    id: "garage",
    designDomainId: "residential",
    displayName: "Garage",
    description: "Гараж — пространство для хранения автомобиля и инвентаря.",
    icon: "🚗",
    metadata: { priority: 11, enabled: true },
  },

  // Commercial
  {
    id: "office",
    designDomainId: "commercial",
    displayName: "Office",
    description: "Офис — рабочее коммерческое пространство общего назначения.",
    icon: "🏢",
    metadata: { priority: 12, enabled: true },
  },
  {
    id: "meeting_room",
    designDomainId: "commercial",
    displayName: "Meeting Room",
    description: "Переговорная — пространство для рабочих встреч.",
    icon: "🗣️",
    metadata: { priority: 13, enabled: true },
  },
  {
    id: "reception",
    designDomainId: "commercial",
    displayName: "Reception",
    description: "Ресепшн — зона приёма посетителей.",
    icon: "💁",
    metadata: { priority: 14, enabled: true },
  },
  {
    id: "coworking",
    designDomainId: "commercial",
    displayName: "Coworking",
    description: "Коворкинг — общее рабочее пространство для разных команд.",
    icon: "🤝",
    metadata: { priority: 15, enabled: true },
  },
  {
    id: "open_office",
    designDomainId: "commercial",
    displayName: "Open Office",
    description: "Открытый офис — рабочее пространство без перегородок.",
    icon: "🖥️",
    metadata: { priority: 16, enabled: true },
  },
  {
    id: "private_office",
    designDomainId: "commercial",
    displayName: "Private Office",
    description: "Личный кабинет — закрытое индивидуальное рабочее пространство.",
    icon: "🚪",
    metadata: { priority: 17, enabled: true },
  },
  {
    id: "shop",
    designDomainId: "commercial",
    displayName: "Shop",
    description: "Магазин — торговое пространство.",
    icon: "🛍️",
    metadata: { priority: 18, enabled: true },
  },
  {
    id: "retail_showroom",
    designDomainId: "commercial",
    displayName: "Retail Showroom",
    description: "Шоу-рум — демонстрационное торговое пространство.",
    icon: "🛒",
    metadata: { priority: 19, enabled: true },
  },
  {
    id: "salon",
    designDomainId: "commercial",
    displayName: "Salon",
    description: "Салон — пространство для бьюти- и сервисных услуг.",
    icon: "💇",
    metadata: { priority: 20, enabled: true },
  },
  {
    id: "gym",
    designDomainId: "commercial",
    displayName: "Gym",
    description: "Спортзал — пространство для тренировок.",
    icon: "🏋️",
    metadata: { priority: 21, enabled: true },
  },
  {
    id: "conference_room",
    designDomainId: "commercial",
    displayName: "Conference Room",
    description: "Конференц-зал — пространство для крупных деловых мероприятий.",
    icon: "📊",
    metadata: { priority: 22, enabled: true },
  },
  {
    id: "exhibition_booth",
    designDomainId: "commercial",
    displayName: "Exhibition Booth",
    description: "Выставочный стенд — временное коммерческое демонстрационное пространство.",
    icon: "📋",
    metadata: { priority: 23, enabled: true },
  },

  // Hospitality
  {
    id: "cafe",
    designDomainId: "hospitality",
    displayName: "Cafe",
    description: "Кафе — пространство для лёгкого питания и напитков.",
    icon: "☕",
    metadata: { priority: 24, enabled: true },
  },
  {
    id: "restaurant",
    designDomainId: "hospitality",
    displayName: "Restaurant",
    description: "Ресторан — пространство для полноценного питания.",
    icon: "🍽️",
    metadata: { priority: 25, enabled: true },
  },
  {
    id: "hotel",
    designDomainId: "hospitality",
    displayName: "Hotel",
    description: "Отель — гостиничный объект в целом.",
    icon: "🏨",
    metadata: { priority: 26, enabled: true },
  },
  {
    id: "hotel_lobby",
    designDomainId: "hospitality",
    displayName: "Hotel Lobby",
    description: "Лобби отеля — зона встречи и ожидания гостей.",
    icon: "🛎️",
    metadata: { priority: 27, enabled: true },
  },
  {
    id: "hotel_room",
    designDomainId: "hospitality",
    displayName: "Hotel Room",
    description: "Номер отеля — пространство для проживания гостей.",
    icon: "🛌",
    metadata: { priority: 28, enabled: true },
  },

  // Industrial
  {
    id: "warehouse",
    designDomainId: "industrial",
    displayName: "Warehouse",
    description: "Склад — пространство для хранения товаров и материалов.",
    icon: "📦",
    metadata: { priority: 29, enabled: true },
  },
  {
    id: "factory",
    designDomainId: "industrial",
    displayName: "Factory",
    description: "Завод — производственное пространство.",
    icon: "🏭",
    metadata: { priority: 30, enabled: true },
  },
  {
    id: "workshop",
    designDomainId: "industrial",
    displayName: "Workshop",
    description: "Мастерская — пространство для ручного/станочного производства.",
    icon: "🔧",
    metadata: { priority: 31, enabled: true },
  },
  {
    id: "laboratory",
    designDomainId: "industrial",
    displayName: "Laboratory",
    description: "Лаборатория — пространство для исследований и тестирования.",
    icon: "🧪",
    metadata: { priority: 32, enabled: true },
  },

  // Healthcare
  {
    id: "hospital_ward",
    designDomainId: "healthcare",
    displayName: "Hospital Ward",
    description: "Больничная палата — пространство для размещения пациентов.",
    icon: "🏥",
    metadata: { priority: 33, enabled: true },
  },
  {
    id: "clinic",
    designDomainId: "healthcare",
    displayName: "Clinic",
    description: "Клиника — амбулаторное медицинское пространство.",
    icon: "⚕️",
    metadata: { priority: 34, enabled: true },
  },
  {
    id: "operating_room",
    designDomainId: "healthcare",
    displayName: "Operating Room",
    description: "Операционная — пространство для хирургических вмешательств.",
    icon: "🩺",
    metadata: { priority: 35, enabled: true },
  },
  {
    id: "waiting_area",
    designDomainId: "healthcare",
    displayName: "Waiting Area",
    description: "Зона ожидания — пространство ожидания приёма.",
    icon: "🪑",
    metadata: { priority: 36, enabled: true },
  },

  // Education
  {
    id: "classroom",
    designDomainId: "education",
    displayName: "Classroom",
    description: "Классная комната — пространство для обучения.",
    icon: "🏫",
    metadata: { priority: 37, enabled: true },
  },
  {
    id: "lecture_hall",
    designDomainId: "education",
    displayName: "Lecture Hall",
    description: "Лекционный зал — пространство для массового обучения.",
    icon: "🎓",
    metadata: { priority: 38, enabled: true },
  },
  {
    id: "library",
    designDomainId: "education",
    displayName: "Library",
    description: "Библиотека — пространство для хранения и чтения литературы.",
    icon: "📚",
    metadata: { priority: 39, enabled: true },
  },

  // Transportation (включая Marine и Aircraft — см. README.md, "Universality")
  {
    id: "airport_terminal",
    designDomainId: "transportation",
    displayName: "Airport Terminal",
    description: "Терминал аэропорта — пространство для обслуживания пассажиров.",
    icon: "✈️",
    metadata: { priority: 40, enabled: true },
  },
  {
    id: "train_station",
    designDomainId: "transportation",
    displayName: "Train Station",
    description: "Железнодорожный вокзал — пространство для обслуживания пассажиров.",
    icon: "🚆",
    metadata: { priority: 41, enabled: true },
  },
  {
    id: "cabin",
    designDomainId: "transportation",
    displayName: "Cabin",
    description: "Каюта — жилое пространство на борту судна.",
    icon: "⛵",
    metadata: { priority: 42, enabled: true },
  },
  {
    id: "deck",
    designDomainId: "transportation",
    displayName: "Deck",
    description: "Палуба — открытое пространство на борту судна.",
    icon: "🚢",
    metadata: { priority: 43, enabled: true },
  },
  {
    id: "passenger_cabin",
    designDomainId: "transportation",
    displayName: "Passenger Cabin",
    description: "Пассажирский салон — пространство для пассажиров на борту воздушного судна.",
    icon: "🛩️",
    metadata: { priority: 44, enabled: true },
  },
  {
    id: "cockpit",
    designDomainId: "transportation",
    displayName: "Cockpit",
    description: "Кабина пилота — рабочее пространство экипажа воздушного судна.",
    icon: "🎛️",
    metadata: { priority: 45, enabled: true },
  },

  // Outdoor
  {
    id: "garden",
    designDomainId: "outdoor",
    displayName: "Garden",
    description: "Сад — открытое озеленённое пространство.",
    icon: "🌷",
    metadata: { priority: 46, enabled: true },
  },
  {
    id: "terrace",
    designDomainId: "outdoor",
    displayName: "Terrace",
    description: "Терраса — примыкающее открытое пространство для отдыха.",
    icon: "🌿",
    metadata: { priority: 47, enabled: true },
  },
  {
    id: "courtyard",
    designDomainId: "outdoor",
    displayName: "Courtyard",
    description: "Внутренний двор — открытое пространство, окружённое застройкой.",
    icon: "🏡",
    metadata: { priority: 48, enabled: true },
  },
  {
    id: "pool_area",
    designDomainId: "outdoor",
    displayName: "Pool Area",
    description: "Зона бассейна — открытое пространство вокруг бассейна.",
    icon: "🏊",
    metadata: { priority: 49, enabled: true },
  },

  // Public (Exhibition)
  {
    id: "museum",
    designDomainId: "public",
    displayName: "Museum",
    description: "Музей — пространство для хранения и показа экспонатов.",
    icon: "🖼️",
    metadata: { priority: 50, enabled: true },
  },
  {
    id: "gallery",
    designDomainId: "public",
    displayName: "Gallery",
    description: "Галерея — пространство для показа произведений искусства.",
    icon: "🎨",
    metadata: { priority: 51, enabled: true },
  },
];
