import type { KnowledgeFeature } from "../core/Feature";

/**
 * Canonical spatial-knowledge records — one `KnowledgeFeature` per
 * canonical Space Type (`SpaceTypeId`, `src/lib/interior/space-type/types.ts`).
 * `domain: "space"` reuses the existing `FeatureType` literal (no new
 * literal introduced — see `./README.md` §3) — records here are simply a
 * second, independently-keyed collection within the same domain, not a
 * new domain literal.
 *
 * `id` is a plain `string` chosen to match the corresponding
 * `SpaceTypeId` value in `src/lib/interior/space-type/space-types.ts` —
 * by convention/documentation only. This file does not import
 * `space-type/**` (type-only or otherwise): Knowledge references Space
 * Type by id, never by import (see `./README.md` §5).
 *
 * Every field describes only general architectural/spatial knowledge —
 * no prompt fragments, no provider hints, no render/camera/generation
 * settings (see `./README.md` §4). Structured knowledge beyond the
 * built-in `KnowledgeFeature` fields (`description`, `tags`, `notes`)
 * lives in `metadata` — extending an existing model field rather than
 * adding a new one (ADR-000 Principle 22, "Metadata" step). The
 * `metadata` shape below is illustrative and consistent across entries,
 * not a TypeScript contract — `KnowledgeFeature.metadata` remains
 * `Readonly<Record<string, unknown>>`, exactly as defined in
 * `../core/Entity.ts`.
 */
export const SPATIAL_KNOWLEDGE_REGISTRY: readonly KnowledgeFeature[] = [
  // ───────────────────────── Residential ─────────────────────────
  {
    id: "living_room",
    type: "feature",
    domain: "space",
    name: "Living Room",
    description:
      "Primary social and relaxation space of a home, organized around seating and a shared focal point.",
    tags: ["residential", "semi-private", "high-traffic", "social"],
    metadata: {
      primaryFunctions: ["relaxation", "socializing", "entertainment"],
      typicalActivities: ["conversation", "watching media", "hosting guests", "reading"],
      spatialPriorities: ["comfortable seating layout", "clear focal point", "open sightlines"],
      functionalZones: ["seating zone", "media/focal zone", "circulation path"],
      privacyLevel: "semi-private",
      trafficLevel: "high",
      circulation: "central hub connecting entry, dining, and private rooms",
      ergonomicConcerns: ["seating depth and height", "screen viewing distance"],
      furnitureCategories: ["sofas", "armchairs", "coffee tables", "media console", "area rug"],
      lightingRequirements: ["layered ambient lighting", "task lighting near seating", "dimmable evening scene"],
      accessibilityConsiderations: ["clear walkways between furniture", "step-free entry"],
      storageNeeds: ["media storage", "occasional-use item storage"],
      safetyConsiderations: ["stable furniture placement", "cable management away from walkways"],
    },
  },
  {
    id: "bedroom",
    type: "feature",
    domain: "space",
    name: "Bedroom",
    description: "Private rest space organized around the bed as the primary functional anchor.",
    tags: ["residential", "private", "low-traffic", "restorative"],
    metadata: {
      primaryFunctions: ["sleep", "rest", "dressing"],
      typicalActivities: ["sleeping", "dressing", "reading before sleep"],
      spatialPriorities: ["bed placement away from drafts/doors", "unobstructed wardrobe access"],
      functionalZones: ["sleeping zone", "dressing zone", "optional seating/reading nook"],
      privacyLevel: "private",
      trafficLevel: "low",
      circulation: "single access point, minimal through-traffic",
      ergonomicConcerns: ["bed height and clearance", "wardrobe reach zones"],
      furnitureCategories: ["bed", "nightstands", "wardrobe/dresser", "seating"],
      lightingRequirements: ["low-glare ambient light", "bedside task lighting", "blackout capability"],
      accessibilityConsiderations: ["clear path from bed to door", "night lighting for safety"],
      storageNeeds: ["clothing storage", "linen storage"],
      safetyConsiderations: ["no trip hazards near bed", "smoke detector proximity"],
    },
  },
  {
    id: "kitchen",
    type: "feature",
    domain: "space",
    name: "Kitchen",
    description: "Food preparation space organized around a functional work triangle of storage, prep, and cooking.",
    tags: ["residential", "semi-private", "high-traffic", "wet-area", "work-intensive"],
    metadata: {
      primaryFunctions: ["food storage", "food preparation", "cooking", "cleanup"],
      typicalActivities: ["cooking", "washing dishes", "food storage retrieval", "casual dining"],
      spatialPriorities: ["efficient work triangle", "counter continuity", "ventilation over cooking zone"],
      functionalZones: ["storage/pantry zone", "prep zone", "cooking zone", "cleanup zone"],
      privacyLevel: "semi-private",
      trafficLevel: "high",
      circulation: "efficient path between storage, prep, and cooking",
      ergonomicConcerns: ["counter height", "reach zones for upper cabinets", "appliance clearance"],
      furnitureCategories: ["cabinetry", "countertops", "kitchen island", "bar stools"],
      lightingRequirements: ["bright task lighting over counters", "under-cabinet lighting", "ambient overhead"],
      accessibilityConsiderations: ["clear turning radius", "reachable storage heights"],
      storageNeeds: ["food storage", "cookware storage", "small appliance storage"],
      safetyConsiderations: ["heat source clearance", "non-slip flooring", "fire suppression proximity", "ventilation"],
      environmentalConstraints: ["moisture exposure", "heat and grease", "requires ventilation/extraction"],
    },
  },
  {
    id: "dining_room",
    type: "feature",
    domain: "space",
    name: "Dining Room",
    description: "Space dedicated to shared meals, organized around a central table.",
    tags: ["residential", "semi-private", "moderate-traffic", "social"],
    metadata: {
      primaryFunctions: ["dining", "gathering"],
      typicalActivities: ["eating meals", "hosting dinners", "conversation"],
      spatialPriorities: ["table centrality", "clearance for chair movement", "proximity to kitchen"],
      functionalZones: ["dining table zone", "serving/sideboard zone"],
      privacyLevel: "semi-private",
      trafficLevel: "moderate",
      circulation: "clearance around table for seating and service",
      furnitureCategories: ["dining table", "dining chairs", "sideboard/buffet", "pendant lighting fixture"],
      lightingRequirements: ["focused light over table", "dimmable ambient light"],
      accessibilityConsiderations: ["clearance for wheelchair seating at table"],
      storageNeeds: ["tableware storage", "linen storage"],
      safetyConsiderations: ["stable table/chair construction"],
    },
  },
  {
    id: "bathroom",
    type: "feature",
    domain: "space",
    name: "Bathroom",
    description: "Hygiene space combining wet fixtures with storage in a compact, moisture-controlled footprint.",
    tags: ["residential", "private", "wet-area", "compact"],
    metadata: {
      primaryFunctions: ["hygiene", "grooming"],
      typicalActivities: ["bathing/showering", "grooming", "toileting"],
      spatialPriorities: ["clear wet/dry separation", "ventilation", "waterproofing"],
      functionalZones: ["wet zone (shower/tub)", "vanity zone", "toilet zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      circulation: "compact, single-user oriented",
      ergonomicConcerns: ["vanity height", "grab bar placement", "shower controls reach"],
      furnitureCategories: ["vanity", "mirror", "storage cabinet"],
      lightingRequirements: ["shadow-free vanity lighting", "moisture-rated fixtures"],
      accessibilityConsiderations: ["grab bars", "non-slip flooring", "step-free shower entry"],
      storageNeeds: ["toiletries storage", "towel storage"],
      safetyConsiderations: ["slip resistance", "electrical safety near water", "scald protection"],
      environmentalConstraints: ["high humidity", "requires ventilation/extraction"],
    },
  },
  {
    id: "home_office",
    type: "feature",
    domain: "space",
    name: "Home Office",
    description: "Dedicated workspace within a home, supporting focused individual work.",
    tags: ["residential", "private", "low-traffic", "work-intensive"],
    metadata: {
      primaryFunctions: ["focused work", "video calls", "document storage"],
      typicalActivities: ["computer work", "video conferencing", "reading/writing"],
      spatialPriorities: ["minimized visual/acoustic distraction", "natural light without screen glare"],
      functionalZones: ["desk/work zone", "storage/reference zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      circulation: "isolated from household through-traffic where possible",
      ergonomicConcerns: ["desk and chair height", "monitor eye-line", "keyboard/mouse reach"],
      furnitureCategories: ["desk", "task chair", "shelving/storage"],
      lightingRequirements: ["glare-free task lighting", "balanced ambient light for video calls"],
      acousticExpectations: "low background noise for calls and concentration",
      storageNeeds: ["document storage", "equipment storage"],
      safetyConsiderations: ["cable management", "ergonomic strain prevention"],
    },
  },
  {
    id: "hallway",
    type: "feature",
    domain: "space",
    name: "Hallway",
    description: "Connective circulation space linking rooms within a residence.",
    tags: ["residential", "circulation", "transitional"],
    metadata: {
      primaryFunctions: ["circulation", "transition between rooms"],
      typicalActivities: ["passing through", "brief storage access"],
      spatialPriorities: ["unobstructed width", "clear sightlines to adjoining doors"],
      functionalZones: ["circulation path"],
      privacyLevel: "semi-private",
      trafficLevel: "high",
      circulation: "primary connective path between rooms",
      furnitureCategories: ["console table", "wall-mounted storage"],
      lightingRequirements: ["even ambient lighting", "night lighting for safety"],
      accessibilityConsiderations: ["minimum clear width for mobility aids", "no protruding obstacles"],
      safetyConsiderations: ["clear egress path", "adequate lighting to avoid trips"],
    },
  },
  {
    id: "closet",
    type: "feature",
    domain: "space",
    name: "Closet",
    description: "Compact enclosed storage space for clothing and personal items.",
    tags: ["residential", "private", "storage-intensive", "compact"],
    metadata: {
      primaryFunctions: ["clothing storage", "organization"],
      typicalActivities: ["dressing", "organizing belongings"],
      spatialPriorities: ["maximized storage density", "reachable shelving/rod heights"],
      functionalZones: ["hanging zone", "shelving zone", "folded storage zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      ergonomicConcerns: ["reach height for rods and shelves"],
      furnitureCategories: ["shelving", "hanging rods", "drawer units"],
      lightingRequirements: ["bright, even interior lighting"],
      storageNeeds: ["clothing storage", "accessory storage", "seasonal item storage"],
      safetyConsiderations: ["stable shelving anchored to walls"],
    },
  },
  {
    id: "laundry",
    type: "feature",
    domain: "space",
    name: "Laundry",
    description: "Utility space for washing, drying, and folding laundry.",
    tags: ["residential", "wet-area", "utility"],
    metadata: {
      primaryFunctions: ["washing", "drying", "folding/sorting"],
      typicalActivities: ["loading/unloading machines", "folding", "sorting"],
      spatialPriorities: ["appliance clearance", "ventilation for dryer exhaust", "durable water-resistant surfaces"],
      functionalZones: ["washing zone", "drying zone", "folding/sorting zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      ergonomicConcerns: ["counter/folding surface height", "appliance loading height"],
      furnitureCategories: ["washer/dryer units", "folding counter", "storage cabinets"],
      lightingRequirements: ["bright task lighting"],
      storageNeeds: ["detergent/supply storage", "linen storage"],
      safetyConsiderations: ["ventilation for dryer exhaust", "water leak protection", "non-slip flooring"],
      environmentalConstraints: ["moisture exposure", "vibration from appliances"],
    },
  },
  {
    id: "balcony",
    type: "feature",
    domain: "space",
    name: "Balcony",
    description: "Small outdoor extension of a residence, exposed to the elements.",
    tags: ["residential", "outdoor", "semi-private", "compact"],
    metadata: {
      primaryFunctions: ["outdoor relaxation", "transitional outdoor space"],
      typicalActivities: ["sitting outdoors", "light gardening", "views"],
      spatialPriorities: ["structural load limits", "weatherproof materials", "safety railing"],
      functionalZones: ["seating zone", "planting zone"],
      privacyLevel: "semi-private",
      trafficLevel: "low",
      furnitureCategories: ["outdoor seating", "planters", "small table"],
      lightingRequirements: ["weatherproof outdoor lighting"],
      accessibilityConsiderations: ["level, step-free threshold from interior"],
      safetyConsiderations: ["railing height and load rating", "weather exposure of materials"],
      environmentalConstraints: ["direct weather exposure", "load capacity limits"],
    },
  },
  {
    id: "garage",
    type: "feature",
    domain: "space",
    name: "Garage",
    description: "Utility space for vehicle storage and general equipment storage.",
    tags: ["residential", "utility", "storage-intensive"],
    metadata: {
      primaryFunctions: ["vehicle storage", "equipment/tool storage"],
      typicalActivities: ["parking", "basic maintenance", "storage retrieval"],
      spatialPriorities: ["vehicle maneuvering clearance", "durable flooring", "large door access"],
      functionalZones: ["vehicle bay", "storage/shelving zone", "workbench zone"],
      privacyLevel: "semi-private",
      trafficLevel: "low",
      furnitureCategories: ["shelving units", "workbench", "wall-mounted storage"],
      lightingRequirements: ["bright, even overhead lighting"],
      storageNeeds: ["tool storage", "seasonal item storage"],
      safetyConsiderations: ["ventilation for fumes", "fire safety around stored chemicals", "clear egress"],
      environmentalConstraints: ["temperature extremes", "exhaust/fume exposure"],
    },
  },

  // ───────────────────────── Commercial ─────────────────────────
  {
    id: "office",
    type: "feature",
    domain: "space",
    name: "Office",
    description: "General-purpose commercial workspace supporting individual and collaborative work.",
    tags: ["commercial", "semi-public", "moderate-traffic", "work-intensive"],
    metadata: {
      primaryFunctions: ["individual work", "collaboration", "administration"],
      typicalActivities: ["desk work", "meetings", "phone/video calls"],
      spatialPriorities: ["workstation efficiency", "acoustic separation", "daylight access"],
      functionalZones: ["workstation zone", "meeting/collaboration zone", "circulation"],
      privacyLevel: "semi-private",
      trafficLevel: "moderate",
      ergonomicConcerns: ["desk/chair adjustability", "monitor placement"],
      furnitureCategories: ["desks", "task chairs", "storage cabinets", "meeting tables"],
      lightingRequirements: ["even task lighting", "daylight balance", "glare control on screens"],
      accessibilityConsiderations: ["clear circulation widths", "adjustable-height workstations"],
      acousticExpectations: "moderate noise control between workstations and meeting areas",
      storageNeeds: ["document/file storage", "personal storage"],
      safetyConsiderations: ["clear emergency egress", "cable management"],
      occupancyCharacteristics: "sustained multi-hour occupancy on business days",
    },
  },
  {
    id: "meeting_room",
    type: "feature",
    domain: "space",
    name: "Meeting Room",
    description: "Enclosed space for focused group discussion and decision-making.",
    tags: ["commercial", "private", "moderate-traffic", "collaborative"],
    metadata: {
      primaryFunctions: ["group discussion", "presentations", "decision-making"],
      typicalActivities: ["meetings", "presentations", "video conferencing"],
      spatialPriorities: ["sightlines to shared display", "acoustic isolation from adjacent spaces"],
      functionalZones: ["conferencing table zone", "presentation/display zone"],
      privacyLevel: "private",
      trafficLevel: "moderate",
      furnitureCategories: ["conference table", "meeting chairs", "display/screen mount"],
      lightingRequirements: ["dimmable lighting for presentations", "glare-free display viewing"],
      acousticExpectations: "sound isolation from adjacent workspaces for confidentiality",
      accessibilityConsiderations: ["clear access for all seating positions"],
      safetyConsiderations: ["clear egress path"],
      occupancyCharacteristics: "short, scheduled group sessions",
    },
  },
  {
    id: "reception",
    type: "feature",
    domain: "space",
    name: "Reception",
    description: "First point of contact for visitors, combining greeting, waiting, and light administration.",
    tags: ["commercial", "public", "high-traffic", "first-impression"],
    metadata: {
      primaryFunctions: ["visitor greeting", "check-in/registration", "waiting"],
      typicalActivities: ["greeting visitors", "waiting", "brief administration"],
      spatialPriorities: ["clear visitor sightline on entry", "welcoming first impression", "desk visibility"],
      functionalZones: ["reception desk zone", "waiting/seating zone"],
      privacyLevel: "public",
      trafficLevel: "high",
      circulation: "primary entry point funneling visitors to destinations",
      furnitureCategories: ["reception desk", "waiting seating", "signage"],
      lightingRequirements: ["welcoming ambient lighting", "task lighting at desk"],
      accessibilityConsiderations: ["step-free entry", "accessible desk height", "wayfinding signage"],
      occupancyCharacteristics: "high visitor turnover, brief dwell time",
    },
  },
  {
    id: "coworking",
    type: "feature",
    domain: "space",
    name: "Coworking",
    description: "Shared flexible workspace serving multiple independent individuals or teams.",
    tags: ["commercial", "semi-public", "high-traffic", "flexible"],
    metadata: {
      primaryFunctions: ["shared individual work", "networking", "flexible team work"],
      typicalActivities: ["desk work", "informal meetings", "networking"],
      spatialPriorities: ["flexible furniture arrangement", "varied work-setting choices", "shared amenity access"],
      functionalZones: ["hot-desk zone", "informal lounge zone", "bookable meeting zone"],
      privacyLevel: "semi-public",
      trafficLevel: "high",
      furnitureCategories: ["shared desks", "lounge seating", "lockers"],
      lightingRequirements: ["bright, even ambient lighting across varied zones"],
      acousticExpectations: "zoned acoustic control between focus and social areas",
      storageNeeds: ["personal locker storage"],
      accessibilityConsiderations: ["variety of accessible seating heights"],
      occupancyCharacteristics: "high daily turnover of unrelated occupants",
    },
  },
  {
    id: "open_office",
    type: "feature",
    domain: "space",
    name: "Open Office",
    description: "Large, unpartitioned workspace accommodating many workstations in one continuous floor plate.",
    tags: ["commercial", "semi-private", "high-traffic", "work-intensive"],
    metadata: {
      primaryFunctions: ["large-scale individual work", "team collaboration"],
      typicalActivities: ["desk work", "informal collaboration"],
      spatialPriorities: ["workstation density", "sightline management", "acoustic zoning"],
      functionalZones: ["workstation clusters", "informal collaboration pockets"],
      privacyLevel: "semi-private",
      trafficLevel: "high",
      ergonomicConcerns: ["desk spacing", "shared equipment reach"],
      furnitureCategories: ["desk clusters", "task chairs", "mobile partitions/screens"],
      lightingRequirements: ["uniform overhead lighting", "reduced glare across large floor plate"],
      acousticExpectations: "significant acoustic management needed to control ambient noise buildup",
      safetyConsiderations: ["clear multi-directional egress paths"],
      occupancyCharacteristics: "high density, sustained daytime occupancy",
    },
  },
  {
    id: "private_office",
    type: "feature",
    domain: "space",
    name: "Private Office",
    description: "Enclosed individual workspace offering acoustic and visual privacy.",
    tags: ["commercial", "private", "low-traffic", "work-intensive"],
    metadata: {
      primaryFunctions: ["focused individual work", "confidential conversations"],
      typicalActivities: ["desk work", "private calls/meetings"],
      spatialPriorities: ["acoustic enclosure", "controlled visual privacy"],
      functionalZones: ["desk zone", "small meeting/seating zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      furnitureCategories: ["executive desk", "task chair", "guest seating", "storage cabinet"],
      lightingRequirements: ["individually controllable lighting", "daylight access where possible"],
      acousticExpectations: "full enclosure for confidential conversations",
      storageNeeds: ["document storage"],
    },
  },
  {
    id: "shop",
    type: "feature",
    domain: "space",
    name: "Shop",
    description: "General retail space organized to display merchandise and facilitate purchases.",
    tags: ["commercial", "public", "high-traffic", "retail"],
    metadata: {
      primaryFunctions: ["merchandise display", "sales transactions", "browsing"],
      typicalActivities: ["browsing", "trying/inspecting products", "checkout"],
      spatialPriorities: ["clear sightlines to merchandise", "logical browsing path", "checkout visibility"],
      functionalZones: ["display/merchandising zone", "checkout zone", "back-of-house storage"],
      privacyLevel: "public",
      trafficLevel: "high",
      circulation: "guided browsing path leading toward checkout",
      furnitureCategories: ["display fixtures/shelving", "checkout counter", "signage"],
      lightingRequirements: ["accent lighting on merchandise", "even ambient lighting for browsing"],
      accessibilityConsiderations: ["accessible aisle widths", "accessible checkout height"],
      storageNeeds: ["backroom stock storage"],
      safetyConsiderations: ["clear emergency egress amid fixtures", "loss-prevention sightlines"],
      occupancyCharacteristics: "variable customer volume with peak periods",
    },
  },
  {
    id: "retail_showroom",
    type: "feature",
    domain: "space",
    name: "Retail Showroom",
    description: "Demonstration-oriented retail space emphasizing product presentation over high-volume stock.",
    tags: ["commercial", "public", "moderate-traffic", "retail", "presentation"],
    metadata: {
      primaryFunctions: ["product demonstration", "brand presentation", "consultative sales"],
      typicalActivities: ["product demonstration", "consultation", "browsing curated displays"],
      spatialPriorities: ["generous spacing around featured items", "controlled lighting for presentation"],
      functionalZones: ["feature display zone", "consultation zone"],
      privacyLevel: "public",
      trafficLevel: "moderate",
      furnitureCategories: ["display plinths/platforms", "consultation seating"],
      lightingRequirements: ["accent/spot lighting on featured products", "adjustable presentation lighting"],
      accessibilityConsiderations: ["wide clear paths between displays"],
      occupancyCharacteristics: "lower volume, longer per-visitor dwell time than a general shop",
    },
  },
  {
    id: "salon",
    type: "feature",
    domain: "space",
    name: "Salon",
    description: "Personal-care service space combining service stations with waiting and washing areas.",
    tags: ["commercial", "semi-private", "moderate-traffic", "wet-area", "service"],
    metadata: {
      primaryFunctions: ["beauty/grooming services", "waiting", "washing"],
      typicalActivities: ["hair/beauty treatments", "washing", "waiting"],
      spatialPriorities: ["station spacing for service access", "wet-area separation"],
      functionalZones: ["service station zone", "washing zone", "waiting zone"],
      privacyLevel: "semi-private",
      trafficLevel: "moderate",
      ergonomicConcerns: ["service chair height", "stylist reach and standing comfort"],
      furnitureCategories: ["service chairs", "styling stations", "wash basins", "waiting seating"],
      lightingRequirements: ["bright, true-color task lighting at stations", "flattering mirror lighting"],
      accessibilityConsiderations: ["accessible service station", "clear path to wash area"],
      storageNeeds: ["product/supply storage"],
      safetyConsiderations: ["electrical safety near water", "chemical ventilation"],
      environmentalConstraints: ["moisture exposure at wash zone", "chemical fumes"],
    },
  },
  {
    id: "gym",
    type: "feature",
    domain: "space",
    name: "Gym",
    description: "Physical training space accommodating equipment-based and open-floor exercise.",
    tags: ["commercial", "semi-public", "high-traffic", "active"],
    metadata: {
      primaryFunctions: ["exercise", "strength training", "cardio training"],
      typicalActivities: ["weight training", "cardio exercise", "group classes"],
      spatialPriorities: ["equipment spacing for safe movement", "reinforced flooring", "ventilation"],
      functionalZones: ["cardio zone", "strength/equipment zone", "open floor/stretching zone"],
      privacyLevel: "semi-public",
      trafficLevel: "high",
      ergonomicConcerns: ["equipment clearance zones", "impact-absorbing flooring"],
      furnitureCategories: ["exercise equipment", "storage racks", "mirrors"],
      lightingRequirements: ["bright, energizing lighting", "glare control on mirrors"],
      accessibilityConsiderations: ["accessible equipment options", "clear wide aisles"],
      acousticExpectations: "tolerant of high noise and music levels",
      safetyConsiderations: ["equipment spacing", "impact flooring", "clear emergency egress"],
      environmentalConstraints: ["high ventilation demand", "humidity from exertion"],
    },
  },
  {
    id: "conference_room",
    type: "feature",
    domain: "space",
    name: "Conference Room",
    description: "Larger-scale formal meeting space for significant business gatherings and presentations.",
    tags: ["commercial", "private", "moderate-traffic", "formal", "presentation"],
    metadata: {
      primaryFunctions: ["formal meetings", "presentations", "decision-making at scale"],
      typicalActivities: ["board meetings", "presentations", "video conferencing"],
      spatialPriorities: ["formal table arrangement", "unobstructed presentation sightlines", "acoustic isolation"],
      functionalZones: ["main conferencing table zone", "presentation/display zone"],
      privacyLevel: "private",
      trafficLevel: "moderate",
      furnitureCategories: ["large conference table", "executive chairs", "AV/display equipment"],
      lightingRequirements: ["dimmable presentation lighting", "even ambient lighting for formal tone"],
      acousticExpectations: "high sound isolation for confidential, formal proceedings",
      accessibilityConsiderations: ["accessible seating positions throughout table"],
      occupancyCharacteristics: "scheduled, larger-group sessions",
    },
  },
  {
    id: "exhibition_booth",
    type: "feature",
    domain: "space",
    name: "Exhibition Booth",
    description: "Temporary demonstration space for showcasing a brand or product at an event.",
    tags: ["commercial", "public", "high-traffic", "temporary", "presentation"],
    metadata: {
      primaryFunctions: ["brand presentation", "product demonstration", "lead engagement"],
      typicalActivities: ["demonstrations", "conversations with visitors", "brief presentations"],
      spatialPriorities: ["visibility from aisle", "compact modular footprint", "quick assembly/teardown"],
      functionalZones: ["display/demo zone", "conversation zone", "storage/back zone"],
      privacyLevel: "public",
      trafficLevel: "high",
      furnitureCategories: ["modular display panels", "demo counters", "lightweight seating"],
      lightingRequirements: ["attention-grabbing accent lighting", "portable/temporary fixtures"],
      accessibilityConsiderations: ["clear approach from all aisle sides"],
      occupancyCharacteristics: "very short visitor dwell time, high turnover during event hours",
      environmentalConstraints: ["temporary structure", "shared venue power/space limits"],
    },
  },

  // ───────────────────────── Hospitality ─────────────────────────
  {
    id: "cafe",
    type: "feature",
    domain: "space",
    name: "Cafe",
    description: "Informal food-and-beverage space supporting quick service and casual seated dwell time.",
    tags: ["hospitality", "public", "moderate-traffic", "social", "wet-area"],
    metadata: {
      primaryFunctions: ["beverage/light food service", "casual seating", "social gathering"],
      typicalActivities: ["ordering", "dining/drinking", "working or socializing"],
      spatialPriorities: ["efficient counter/service flow", "varied seating configurations"],
      functionalZones: ["counter/service zone", "seating zone", "prep/back zone"],
      privacyLevel: "public",
      trafficLevel: "moderate",
      furnitureCategories: ["counter seating", "small tables and chairs", "service counter"],
      lightingRequirements: ["warm ambient lighting", "task lighting at counter"],
      accessibilityConsiderations: ["accessible counter height", "clear aisles between tables"],
      acousticExpectations: "tolerant of moderate ambient conversation noise",
      storageNeeds: ["ingredient/supply storage"],
      safetyConsiderations: ["hot beverage/equipment safety at counter", "clear egress between seating"],
      occupancyCharacteristics: "moderate dwell time, frequent turnover",
    },
  },
  {
    id: "restaurant",
    type: "feature",
    domain: "space",
    name: "Restaurant",
    description: "Full-service dining space combining a seated dining floor with kitchen support.",
    tags: ["hospitality", "public", "high-traffic", "social", "service-intensive"],
    metadata: {
      primaryFunctions: ["full-service dining", "food/beverage service"],
      typicalActivities: ["dining", "ordering and service interaction", "socializing"],
      spatialPriorities: ["service staff circulation", "table spacing for comfort and service access"],
      functionalZones: ["dining floor zone", "host/waiting zone", "service/kitchen pass zone"],
      privacyLevel: "public",
      trafficLevel: "high",
      circulation: "distinct guest and staff circulation paths",
      furnitureCategories: ["dining tables", "dining chairs/booths", "host stand"],
      lightingRequirements: ["mood-setting ambient lighting", "task lighting for menus and service"],
      accessibilityConsiderations: ["accessible table heights and spacing", "accessible route to restrooms"],
      acousticExpectations: "managed ambient noise to support conversation at table",
      storageNeeds: ["tableware and linen storage"],
      safetyConsiderations: ["clear service staff paths", "fire safety near kitchen pass"],
      occupancyCharacteristics: "seated dwell time of an hour or more, peak meal-service surges",
    },
  },
  {
    id: "hotel",
    type: "feature",
    domain: "space",
    name: "Hotel",
    description: "Overall hospitality accommodation property combining guest, public, and back-of-house functions.",
    tags: ["hospitality", "public", "high-traffic", "mixed-use"],
    metadata: {
      primaryFunctions: ["guest accommodation", "hospitality services", "public gathering"],
      typicalActivities: ["check-in/out", "lodging", "dining", "events"],
      spatialPriorities: ["clear guest wayfinding", "separation of guest and back-of-house circulation"],
      functionalZones: ["guest room zone", "public/lobby zone", "back-of-house zone"],
      privacyLevel: "semi-public",
      trafficLevel: "high",
      accessibilityConsiderations: ["accessible guest rooms", "accessible public circulation"],
      occupancyCharacteristics: "mixed short-stay guests and continuous staff presence",
      safetyConsiderations: ["fire egress across multiple floors/zones", "24-hour operational safety"],
    },
  },
  {
    id: "hotel_lobby",
    type: "feature",
    domain: "space",
    name: "Hotel Lobby",
    description: "Arrival and gathering space for hotel guests, blending reception with lounge seating.",
    tags: ["hospitality", "public", "high-traffic", "first-impression", "social"],
    metadata: {
      primaryFunctions: ["guest arrival", "check-in/out", "informal gathering"],
      typicalActivities: ["checking in/out", "waiting", "casual socializing"],
      spatialPriorities: ["strong first impression", "clear path to reception desk and elevators"],
      functionalZones: ["reception desk zone", "lounge/seating zone", "concierge zone"],
      privacyLevel: "public",
      trafficLevel: "high",
      circulation: "primary hub connecting entrance, reception, elevators, and amenities",
      furnitureCategories: ["reception desk", "lounge seating", "luggage storage"],
      lightingRequirements: ["statement ambient lighting", "welcoming warm tones"],
      accessibilityConsiderations: ["step-free entry", "accessible reception counter"],
      occupancyCharacteristics: "continuous variable traffic, brief-to-moderate dwell time",
    },
  },
  {
    id: "hotel_room",
    type: "feature",
    domain: "space",
    name: "Hotel Room",
    description: "Private guest accommodation combining sleeping, hygiene, and short-term living functions.",
    tags: ["hospitality", "private", "low-traffic", "restorative"],
    metadata: {
      primaryFunctions: ["sleep", "rest", "short-term living", "hygiene"],
      typicalActivities: ["sleeping", "dressing", "resting", "occasional work"],
      spatialPriorities: ["compact efficient layout", "bed as focal point", "attached bathroom access"],
      functionalZones: ["sleeping zone", "bathroom zone", "small work/luggage zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      furnitureCategories: ["bed", "nightstands", "desk/luggage rack", "wardrobe"],
      lightingRequirements: ["layered ambient and bedside lighting", "blackout capability"],
      accessibilityConsiderations: ["accessible room variants with wider clearances"],
      storageNeeds: ["luggage storage", "clothing storage"],
      safetyConsiderations: ["clear egress to corridor", "smoke detection", "secure door locking"],
      maintenanceCharacteristics: ["durable finishes for frequent guest turnover housekeeping"],
      occupancyCharacteristics: "short-term stays with high turnover between occupants",
    },
  },

  // ───────────────────────── Industrial ─────────────────────────
  {
    id: "warehouse",
    type: "feature",
    domain: "space",
    name: "Warehouse",
    description: "Large-volume storage space optimized for goods handling and logistics.",
    tags: ["industrial", "semi-public", "moderate-traffic", "storage-intensive", "large-scale"],
    metadata: {
      primaryFunctions: ["bulk storage", "goods handling", "logistics staging"],
      typicalActivities: ["loading/unloading", "picking and stocking", "inventory movement"],
      spatialPriorities: ["clear aisle widths for equipment", "high storage density", "loading dock access"],
      functionalZones: ["racking/storage zone", "staging/loading zone", "circulation aisles"],
      privacyLevel: "semi-public",
      trafficLevel: "moderate",
      circulation: "wide aisles sized for forklifts/pallet equipment",
      furnitureCategories: ["storage racking", "pallets", "loading equipment"],
      lightingRequirements: ["high-bay uniform lighting", "task lighting at loading docks"],
      storageNeeds: ["palletized goods storage"],
      safetyConsiderations: ["equipment traffic separation from pedestrians", "load rating of racking", "fire suppression for storage density"],
      environmentalConstraints: ["large unconditioned volume", "temperature/humidity control for sensitive goods"],
    },
  },
  {
    id: "factory",
    type: "feature",
    domain: "space",
    name: "Factory",
    description: "Production space organized around a manufacturing process flow.",
    tags: ["industrial", "semi-public", "moderate-traffic", "process-driven", "large-scale"],
    metadata: {
      primaryFunctions: ["manufacturing", "assembly", "production process flow"],
      typicalActivities: ["assembly line work", "machine operation", "quality inspection"],
      spatialPriorities: ["logical process-flow layout", "equipment clearance", "utility access"],
      functionalZones: ["production line zone", "assembly zone", "quality control zone", "material staging"],
      privacyLevel: "semi-public",
      trafficLevel: "moderate",
      ergonomicConcerns: ["workstation height for repetitive tasks", "machine operator reach zones"],
      furnitureCategories: ["production machinery", "workbenches", "material handling equipment"],
      lightingRequirements: ["high-intensity task lighting at workstations", "uniform ambient lighting"],
      acousticExpectations: "elevated ambient noise from machinery, hearing protection zones",
      safetyConsiderations: ["machine guarding", "clear emergency egress", "hazardous material handling"],
      environmentalConstraints: ["machinery vibration", "ventilation for fumes/particulates"],
    },
  },
  {
    id: "workshop",
    type: "feature",
    domain: "space",
    name: "Workshop",
    description: "Smaller-scale hands-on fabrication space for manual and machine-tool work.",
    tags: ["industrial", "semi-private", "low-traffic", "process-driven"],
    metadata: {
      primaryFunctions: ["fabrication", "repair", "hands-on craft work"],
      typicalActivities: ["hand-tool work", "machine-tool operation", "assembly"],
      spatialPriorities: ["workbench spacing", "tool accessibility", "material staging"],
      functionalZones: ["workbench zone", "machine-tool zone", "material/tool storage"],
      privacyLevel: "semi-private",
      trafficLevel: "low",
      ergonomicConcerns: ["workbench height", "tool reach and storage accessibility"],
      furnitureCategories: ["workbenches", "tool storage", "machine tools"],
      lightingRequirements: ["bright, shadow-free task lighting at benches"],
      storageNeeds: ["tool storage", "raw material storage"],
      safetyConsiderations: ["machine guarding", "dust/fume extraction", "fire safety near flammable materials"],
      environmentalConstraints: ["dust and particulate generation", "ventilation for fumes"],
    },
  },
  {
    id: "laboratory",
    type: "feature",
    domain: "space",
    name: "Laboratory",
    description: "Controlled space for scientific research, testing, and experimentation.",
    tags: ["industrial", "private", "low-traffic", "process-driven", "controlled-environment"],
    metadata: {
      primaryFunctions: ["research", "testing", "sample handling"],
      typicalActivities: ["experimentation", "sample analysis", "equipment calibration"],
      spatialPriorities: ["bench layout for workflow", "contamination control", "utility/gas access at benches"],
      functionalZones: ["wet bench zone", "instrumentation zone", "sample storage zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      ergonomicConcerns: ["bench height", "equipment reach under fume hoods"],
      furnitureCategories: ["lab benches", "fume hoods", "storage cabinets", "lab stools"],
      lightingRequirements: ["bright, consistent, glare-free lighting for precision work"],
      storageNeeds: ["chemical/sample storage with controlled conditions"],
      safetyConsiderations: ["fume extraction", "chemical safety protocols", "emergency shower/eyewash access"],
      environmentalConstraints: ["temperature/humidity control", "contamination control", "requires ventilation"],
    },
  },

  // ───────────────────────── Healthcare ─────────────────────────
  {
    id: "hospital_ward",
    type: "feature",
    domain: "space",
    name: "Hospital Ward",
    description: "Patient care space combining bed accommodation with clinical monitoring access.",
    tags: ["healthcare", "private", "moderate-traffic", "controlled-environment", "accessible"],
    metadata: {
      primaryFunctions: ["patient recovery", "clinical monitoring", "care delivery"],
      typicalActivities: ["patient rest", "clinical checks", "family visits"],
      spatialPriorities: ["clear staff access around bed", "equipment clearance", "infection control"],
      functionalZones: ["patient bed zone", "clinical/staff access zone", "family/visitor zone"],
      privacyLevel: "private",
      trafficLevel: "moderate",
      ergonomicConcerns: ["bed height for patient transfer", "staff reach to monitoring equipment"],
      furnitureCategories: ["hospital bed", "bedside cabinet", "visitor seating", "medical equipment mounts"],
      lightingRequirements: ["adjustable patient-friendly lighting", "bright clinical task lighting"],
      accessibilityConsiderations: ["wheelchair and gurney clearance", "accessible call systems"],
      acousticExpectations: "controlled noise for patient rest and privacy",
      safetyConsiderations: ["infection control surfaces", "emergency call access", "clear evacuation path"],
      environmentalConstraints: ["requires cleanable, antimicrobial-compatible surfaces"],
    },
  },
  {
    id: "clinic",
    type: "feature",
    domain: "space",
    name: "Clinic",
    description: "Outpatient medical space combining examination, consultation, and waiting functions.",
    tags: ["healthcare", "semi-private", "moderate-traffic", "controlled-environment"],
    metadata: {
      primaryFunctions: ["outpatient consultation", "examination", "minor treatment"],
      typicalActivities: ["consultation", "examination", "waiting"],
      spatialPriorities: ["clear separation of waiting and clinical areas", "privacy during examination"],
      functionalZones: ["waiting zone", "consultation zone", "examination zone"],
      privacyLevel: "semi-private",
      trafficLevel: "moderate",
      furnitureCategories: ["examination table", "consultation desk/seating", "medical storage cabinets"],
      lightingRequirements: ["bright, accurate clinical lighting in exam areas", "calmer ambient lighting in waiting"],
      accessibilityConsiderations: ["accessible examination room layout", "accessible waiting seating"],
      acousticExpectations: "sound isolation for consultation privacy",
      storageNeeds: ["medical supply storage"],
      safetyConsiderations: ["infection control", "controlled medication storage"],
    },
  },
  {
    id: "operating_room",
    type: "feature",
    domain: "space",
    name: "Operating Room",
    description: "Highly controlled surgical space prioritizing sterility, precision, and equipment access.",
    tags: ["healthcare", "private", "low-traffic", "controlled-environment", "sterile"],
    metadata: {
      primaryFunctions: ["surgical procedures", "sterile intervention"],
      typicalActivities: ["surgery", "anesthesia administration", "sterile equipment handling"],
      spatialPriorities: ["sterility control", "equipment/staff clearance around operating table", "controlled air handling"],
      functionalZones: ["sterile operating field zone", "surgical team zone", "equipment/supply zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      ergonomicConcerns: ["surgical table height", "surgical team reach and posture"],
      furnitureCategories: ["operating table", "surgical lighting rig", "equipment booms/carts"],
      lightingRequirements: ["shadow-free high-intensity surgical lighting"],
      accessibilityConsiderations: ["clear clearance for equipment and gurney transfer"],
      acousticExpectations: "controlled, low-distraction acoustic environment",
      maintenanceCharacteristics: ["seamless, fully cleanable, antimicrobial surfaces", "strict sterilization protocols"],
      safetyConsiderations: ["sterile field integrity", "controlled air filtration/pressure", "emergency power redundancy"],
      environmentalConstraints: ["strict temperature/humidity/air-pressure control", "contamination control"],
    },
  },
  {
    id: "waiting_area",
    type: "feature",
    domain: "space",
    name: "Waiting Area",
    description: "Seating space for people awaiting a scheduled service or appointment.",
    tags: ["healthcare", "public", "moderate-traffic", "seated"],
    metadata: {
      primaryFunctions: ["waiting", "queuing for service"],
      typicalActivities: ["sitting", "reading/using devices", "brief conversation"],
      spatialPriorities: ["clear sightline to service point/announcement", "comfortable seating density"],
      functionalZones: ["seating zone", "check-in/queue zone"],
      privacyLevel: "public",
      trafficLevel: "moderate",
      furnitureCategories: ["waiting seating", "side tables", "signage/display"],
      lightingRequirements: ["calm, even ambient lighting"],
      accessibilityConsiderations: ["accessible seating and clear aisles", "visible and audible call systems"],
      acousticExpectations: "moderate noise tolerance with calming background level",
      occupancyCharacteristics: "variable dwell time dependent on service delays",
    },
  },

  // ───────────────────────── Education ─────────────────────────
  {
    id: "classroom",
    type: "feature",
    domain: "space",
    name: "Classroom",
    description: "Instructional space organized around an instructor focal point and student seating.",
    tags: ["education", "semi-public", "moderate-traffic", "instructional"],
    metadata: {
      primaryFunctions: ["instruction", "learning", "group activities"],
      typicalActivities: ["lectures", "group work", "discussions"],
      spatialPriorities: ["clear sightlines to instructional focal point", "flexible seating arrangement"],
      functionalZones: ["instructor/presentation zone", "student seating zone", "group work zone"],
      privacyLevel: "semi-public",
      trafficLevel: "moderate",
      furnitureCategories: ["student desks/chairs", "instructor desk", "presentation board/screen"],
      lightingRequirements: ["even ambient lighting", "glare control on presentation surfaces"],
      accessibilityConsiderations: ["accessible desk arrangement", "clear aisles for mobility aids"],
      acousticExpectations: "controlled reverberation for speech intelligibility",
      storageNeeds: ["classroom material storage"],
      safetyConsiderations: ["clear emergency egress", "stable furniture for active use"],
      occupancyCharacteristics: "scheduled, session-based group occupancy",
    },
  },
  {
    id: "lecture_hall",
    type: "feature",
    domain: "space",
    name: "Lecture Hall",
    description: "Large-capacity instructional space with tiered or fixed seating facing a presentation focal point.",
    tags: ["education", "public", "high-traffic", "instructional", "large-scale"],
    metadata: {
      primaryFunctions: ["large-group instruction", "presentations"],
      typicalActivities: ["lectures", "presentations", "note-taking"],
      spatialPriorities: ["sightlines from every seat", "acoustic projection to full room", "efficient ingress/egress"],
      functionalZones: ["presenter/stage zone", "tiered seating zone"],
      privacyLevel: "public",
      trafficLevel: "high",
      furnitureCategories: ["tiered/fixed seating", "lectern", "large presentation screen"],
      lightingRequirements: ["dimmable house lighting", "focused presenter lighting"],
      accessibilityConsiderations: ["accessible seating positions at multiple tiers", "accessible route to stage"],
      acousticExpectations: "sound reinforcement and controlled reverberation for large-room speech clarity",
      safetyConsiderations: ["multiple emergency egress routes for high occupancy"],
      occupancyCharacteristics: "large simultaneous occupancy with scheduled start/end times",
    },
  },
  {
    id: "library",
    type: "feature",
    domain: "space",
    name: "Library",
    description: "Space for storing, browsing, and quietly using reading and reference materials.",
    tags: ["education", "public", "moderate-traffic", "quiet"],
    metadata: {
      primaryFunctions: ["material storage/archiving", "reading", "quiet study"],
      typicalActivities: ["browsing shelves", "reading", "quiet individual study"],
      spatialPriorities: ["shelving organization and wayfinding", "quiet zone separation from active zones"],
      functionalZones: ["stacks/shelving zone", "reading/study zone", "circulation desk zone"],
      privacyLevel: "public",
      trafficLevel: "moderate",
      ergonomicConcerns: ["shelf reach heights", "study seating comfort for long sessions"],
      furnitureCategories: ["shelving/stacks", "reading tables and chairs", "circulation desk"],
      lightingRequirements: ["even reading-level task lighting", "glare-free shelving illumination"],
      accessibilityConsiderations: ["accessible shelf heights", "wide aisles between stacks"],
      acousticExpectations: "low ambient noise, quiet-zone enforcement",
      storageNeeds: ["archival/collection storage"],
      safetyConsiderations: ["shelving stability/anchoring", "clear aisle egress"],
    },
  },

  // ───────────────────────── Transportation ─────────────────────────
  {
    id: "airport_terminal",
    type: "feature",
    domain: "space",
    name: "Airport Terminal",
    description: "Large-scale passenger processing space combining wayfinding, queuing, and waiting functions.",
    tags: ["transportation", "public", "very-high-traffic", "wayfinding-intensive", "large-scale"],
    metadata: {
      primaryFunctions: ["passenger processing", "wayfinding", "waiting", "retail/dining access"],
      typicalActivities: ["check-in/security processing", "walking long distances", "waiting at gates"],
      spatialPriorities: ["clear large-scale wayfinding", "queue management", "high-volume circulation capacity"],
      functionalZones: ["check-in/processing zone", "security zone", "gate/waiting zone", "concourse retail zone"],
      privacyLevel: "public",
      trafficLevel: "very-high",
      circulation: "high-capacity linear and radial flows toward gates",
      furnitureCategories: ["queuing systems", "gate seating", "signage/wayfinding displays"],
      lightingRequirements: ["bright, consistent large-volume lighting", "daylight integration where possible"],
      accessibilityConsiderations: ["accessible routes across long distances", "clear multilingual wayfinding"],
      acousticExpectations: "public announcement audibility amid high ambient noise",
      safetyConsiderations: ["mass-occupancy emergency egress", "security screening zones"],
      occupancyCharacteristics: "very high, continuous, transient passenger volume",
      environmentalConstraints: ["large-volume climate control", "24-hour operation"],
    },
  },
  {
    id: "train_station",
    type: "feature",
    domain: "space",
    name: "Train Station",
    description: "Passenger transit space combining ticketing, waiting, and platform access.",
    tags: ["transportation", "public", "high-traffic", "wayfinding-intensive"],
    metadata: {
      primaryFunctions: ["passenger transit", "ticketing", "waiting", "platform access"],
      typicalActivities: ["ticket purchase", "waiting", "walking to platforms"],
      spatialPriorities: ["clear wayfinding to platforms", "queue management at ticketing", "weather-protected waiting"],
      functionalZones: ["ticketing/concourse zone", "waiting zone", "platform access zone"],
      privacyLevel: "public",
      trafficLevel: "high",
      circulation: "flow from entrance through concourse to platforms",
      furnitureCategories: ["waiting seating", "ticketing kiosks/counters", "signage/displays"],
      lightingRequirements: ["bright concourse lighting", "platform safety lighting"],
      accessibilityConsiderations: ["accessible platform access (ramps/lifts)", "tactile wayfinding for platform edges"],
      acousticExpectations: "audible announcements amid transit noise",
      safetyConsiderations: ["platform edge safety", "mass-occupancy emergency egress"],
      occupancyCharacteristics: "peak commuter surges with off-peak lulls",
    },
  },
  {
    id: "cabin",
    type: "feature",
    domain: "space",
    name: "Cabin",
    description: "Compact onboard living space aboard a marine vessel, combining sleeping and storage in a constrained footprint.",
    tags: ["transportation", "marine", "private", "compact", "restorative"],
    metadata: {
      primaryFunctions: ["sleep", "rest", "compact storage"],
      typicalActivities: ["sleeping", "dressing", "resting"],
      spatialPriorities: ["space-efficient built-in furniture", "secure storage against vessel motion"],
      functionalZones: ["berth/sleeping zone", "compact storage zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      ergonomicConcerns: ["low headroom clearance", "compact furniture reach"],
      furnitureCategories: ["built-in berth/bunk", "fitted storage", "fold-away furniture"],
      lightingRequirements: ["compact task and ambient lighting", "portholes/daylight where available"],
      storageNeeds: ["secured personal item storage"],
      safetyConsiderations: ["secured furniture and fittings against vessel motion", "clear egress in confined space"],
      environmentalConstraints: ["motion/vibration from vessel", "moisture exposure", "strict weight and space limits"],
    },
  },
  {
    id: "deck",
    type: "feature",
    domain: "space",
    name: "Deck",
    description: "Open exterior space aboard a marine vessel used for circulation, leisure, and operations.",
    tags: ["transportation", "marine", "outdoor", "semi-public"],
    metadata: {
      primaryFunctions: ["outdoor leisure", "circulation", "vessel operations access"],
      typicalActivities: ["walking", "sitting/lounging", "operational tasks"],
      spatialPriorities: ["slip-resistant surfaces", "railing safety", "weatherproof furnishings"],
      functionalZones: ["leisure/seating zone", "circulation walkway", "operational access zone"],
      privacyLevel: "semi-public",
      trafficLevel: "moderate",
      furnitureCategories: ["weatherproof seating", "railings", "fixed deck fittings"],
      lightingRequirements: ["weatherproof navigation-compliant outdoor lighting"],
      accessibilityConsiderations: ["secure handholds", "non-slip walking surfaces"],
      safetyConsiderations: ["railing height and load rating", "slip resistance", "man-overboard prevention"],
      environmentalConstraints: ["direct weather and salt exposure", "vessel motion"],
    },
  },
  {
    id: "passenger_cabin",
    type: "feature",
    domain: "space",
    name: "Passenger Cabin",
    description: "Aircraft interior space accommodating seated passengers for the duration of a flight.",
    tags: ["transportation", "aviation", "semi-private", "high-density", "compact"],
    metadata: {
      primaryFunctions: ["passenger seating", "in-flight rest", "in-flight service"],
      typicalActivities: ["sitting", "resting", "receiving in-flight service"],
      spatialPriorities: ["seat pitch/density optimization", "aisle clearance", "overhead storage access"],
      functionalZones: ["seating rows", "aisle circulation", "galley/service zone"],
      privacyLevel: "semi-private",
      trafficLevel: "moderate",
      ergonomicConcerns: ["seat pitch and recline", "overhead bin reach"],
      furnitureCategories: ["passenger seats", "overhead storage bins", "tray tables"],
      lightingRequirements: ["dimmable cabin ambient lighting", "individual reading lights"],
      accessibilityConsiderations: ["accessible seating rows", "aisle chair compatibility"],
      acousticExpectations: "tolerant of sustained engine/cabin ambient noise",
      safetyConsiderations: ["certified restraint systems", "clear emergency exit rows", "secured overhead storage"],
      environmentalConstraints: ["pressurized cabin", "strict weight and material certification limits"],
      occupancyCharacteristics: "fixed-duration, high-density seated occupancy for flight length",
    },
  },
  {
    id: "cockpit",
    type: "feature",
    domain: "space",
    name: "Cockpit",
    description: "Highly specialized aircraft control space for the flight crew, prioritizing instrument access and precision.",
    tags: ["transportation", "aviation", "private", "compact", "controlled-environment"],
    metadata: {
      primaryFunctions: ["flight control", "navigation", "system monitoring"],
      typicalActivities: ["piloting", "instrument monitoring", "crew coordination"],
      spatialPriorities: ["instrument reach and visibility", "seat positioning relative to controls", "unobstructed forward view"],
      functionalZones: ["pilot seating/control zone", "instrument panel zone"],
      privacyLevel: "private",
      trafficLevel: "low",
      ergonomicConcerns: ["seat adjustability for reach to controls", "instrument panel readability angles"],
      furnitureCategories: ["pilot seats", "control yoke/console", "instrument panel"],
      lightingRequirements: ["low-glare instrument lighting", "night-vision-compatible dimming"],
      safetyConsiderations: ["restraint systems", "redundant instrument access", "strict certification of all fittings"],
      environmentalConstraints: ["pressurized, highly regulated environment", "extremely limited spatial tolerances"],
      occupancyCharacteristics: "fixed small crew occupancy for flight duration",
    },
  },

  // ───────────────────────── Outdoor ─────────────────────────
  {
    id: "garden",
    type: "feature",
    domain: "space",
    name: "Garden",
    description: "Open planted outdoor space combining vegetation with paths and gathering areas.",
    tags: ["outdoor", "semi-private", "low-traffic", "planted"],
    metadata: {
      primaryFunctions: ["planting/cultivation", "outdoor relaxation", "aesthetic landscaping"],
      typicalActivities: ["gardening", "strolling", "sitting outdoors"],
      spatialPriorities: ["planting bed organization", "path circulation", "drainage"],
      functionalZones: ["planting beds", "pathway zone", "seating/gathering zone"],
      privacyLevel: "semi-private",
      trafficLevel: "low",
      furnitureCategories: ["outdoor seating", "planters/beds", "pergolas/shade structures"],
      lightingRequirements: ["weatherproof accent and path lighting"],
      accessibilityConsiderations: ["firm, level pathway surfaces"],
      safetyConsiderations: ["even path surfaces to avoid trips", "weather-resistant structures"],
      environmentalConstraints: ["full weather exposure", "seasonal variation", "irrigation/drainage needs"],
    },
  },
  {
    id: "terrace",
    type: "feature",
    domain: "space",
    name: "Terrace",
    description: "Open outdoor extension attached to a building, used for relaxation and dining.",
    tags: ["outdoor", "semi-private", "moderate-traffic", "social"],
    metadata: {
      primaryFunctions: ["outdoor relaxation", "outdoor dining", "gathering"],
      typicalActivities: ["sitting", "outdoor dining", "socializing"],
      spatialPriorities: ["weather-resistant furnishing", "shade/sun control", "level, stable flooring"],
      functionalZones: ["seating/lounge zone", "dining zone"],
      privacyLevel: "semi-private",
      trafficLevel: "moderate",
      furnitureCategories: ["outdoor seating", "outdoor dining sets", "shade structures/umbrellas"],
      lightingRequirements: ["weatherproof ambient and accent lighting"],
      accessibilityConsiderations: ["step-free connection to interior"],
      safetyConsiderations: ["railing/edge protection where elevated", "weather-resistant materials"],
      environmentalConstraints: ["direct weather exposure"],
    },
  },
  {
    id: "courtyard",
    type: "feature",
    domain: "space",
    name: "Courtyard",
    description: "Open-air outdoor space enclosed by surrounding built structure.",
    tags: ["outdoor", "semi-private", "low-traffic", "enclosed"],
    metadata: {
      primaryFunctions: ["outdoor gathering", "passive recreation", "daylighting for surrounding rooms"],
      typicalActivities: ["sitting", "walking through", "informal gathering"],
      spatialPriorities: ["enclosure-driven microclimate", "shared sightlines from surrounding rooms"],
      functionalZones: ["central open zone", "perimeter seating/planting"],
      privacyLevel: "semi-private",
      trafficLevel: "low",
      furnitureCategories: ["outdoor seating", "planters", "water feature (optional)"],
      lightingRequirements: ["ambient and accent lighting visible from surrounding interiors"],
      accessibilityConsiderations: ["level surfaces connecting all surrounding entries"],
      safetyConsiderations: ["drainage to prevent pooling", "even walking surfaces"],
      environmentalConstraints: ["enclosed microclimate", "drainage requirements"],
    },
  },
  {
    id: "pool_area",
    type: "feature",
    domain: "space",
    name: "Pool Area",
    description: "Open outdoor space centered on a swimming pool, combining water, lounging, and circulation zones.",
    tags: ["outdoor", "semi-private", "moderate-traffic", "wet-area", "leisure"],
    metadata: {
      primaryFunctions: ["swimming", "sunbathing/lounging", "poolside gathering"],
      typicalActivities: ["swimming", "lounging", "socializing poolside"],
      spatialPriorities: ["slip-resistant deck surfaces", "clear sightlines for supervision", "drainage around pool edge"],
      functionalZones: ["water zone", "lounging/deck zone", "shade zone"],
      privacyLevel: "semi-private",
      trafficLevel: "moderate",
      furnitureCategories: ["loungers", "outdoor seating", "shade umbrellas/cabanas"],
      lightingRequirements: ["underwater pool lighting", "weatherproof deck lighting"],
      accessibilityConsiderations: ["pool access lift/ramp", "non-slip accessible paths"],
      safetyConsiderations: ["slip-resistant decking", "pool fencing/barriers", "clear supervision sightlines"],
      environmentalConstraints: ["chemical water treatment exposure", "direct weather exposure", "drainage requirements"],
    },
  },

  // ───────────────────────── Public ─────────────────────────
  {
    id: "museum",
    type: "feature",
    domain: "space",
    name: "Museum",
    description: "Public exhibition space designed to protect and present curated collections to visitors.",
    tags: ["public", "public-access", "moderate-traffic", "presentation", "controlled-environment"],
    metadata: {
      primaryFunctions: ["exhibit display", "collection preservation", "public education"],
      typicalActivities: ["viewing exhibits", "guided tours", "self-paced browsing"],
      spatialPriorities: ["controlled lighting for artifact preservation", "clear curated visitor path", "climate control"],
      functionalZones: ["exhibit display zone", "circulation/visitor path", "collection storage (back-of-house)"],
      privacyLevel: "public",
      trafficLevel: "moderate",
      furnitureCategories: ["display cases", "plinths", "wayfinding/interpretive signage"],
      lightingRequirements: ["UV-filtered conservation-grade lighting", "accent lighting on exhibits"],
      accessibilityConsiderations: ["step-free visitor routes", "accessible exhibit viewing heights"],
      acousticExpectations: "quiet, contemplative ambient noise level",
      safetyConsiderations: ["artifact security", "mass-occupancy emergency egress"],
      environmentalConstraints: ["strict temperature/humidity control for conservation", "UV exposure control"],
    },
  },
  {
    id: "gallery",
    type: "feature",
    domain: "space",
    name: "Gallery",
    description: "Public space dedicated to displaying and viewing works of visual art.",
    tags: ["public", "public-access", "moderate-traffic", "presentation"],
    metadata: {
      primaryFunctions: ["artwork display", "public viewing", "sales/exhibition events"],
      typicalActivities: ["viewing artwork", "browsing", "attending openings/events"],
      spatialPriorities: ["neutral backdrop walls", "controlled accent lighting on works", "open, adaptable floor plan"],
      functionalZones: ["display wall zone", "open circulation zone"],
      privacyLevel: "public",
      trafficLevel: "moderate",
      furnitureCategories: ["hanging/display walls", "pedestals", "minimal seating"],
      lightingRequirements: ["adjustable accent lighting on artworks", "neutral, glare-free ambient lighting"],
      accessibilityConsiderations: ["clear open circulation for all visitors"],
      acousticExpectations: "quiet, contemplative ambient noise level",
      safetyConsiderations: ["artwork security", "clear emergency egress"],
    },
  },
];

export function getSpatialKnowledge(id: string): KnowledgeFeature | undefined {
  return SPATIAL_KNOWLEDGE_REGISTRY.find((entry) => entry.id === id);
}

export function getAllSpatialKnowledge(): readonly KnowledgeFeature[] {
  return SPATIAL_KNOWLEDGE_REGISTRY;
}
