import { INTERIOR_STYLE_CATEGORIES } from "./categories";
import type { InteriorStyle } from "./types";

/**
 * Single Source of Truth for all interior styles.
 *
 * Data is losslessly ported from the existing, unsynchronized sources:
 * - displayName / emoji / category / previewImage <- STYLE_DISPLAY + STYLE_CATEGORIES (src/app/components/StylePicker.tsx)
 * - description                                   <- STYLE_DISPLAY[].desc (src/app/components/StylePicker.tsx)
 * - promptFragment                                <- STYLE_DESCRIPTIONS (src/lib/prompts.ts)
 *
 * No text has been rewritten or improved. See ./README.md for how this
 * registry relates to those legacy sources and to future modules.
 */
export const INTERIOR_STYLE_REGISTRY: InteriorStyle[] = [
  // --- popular ---
  {
    id: "minimalist",
    slug: "minimalist",
    displayName: "Минимализм",
    emoji: "⬜",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Чистые линии, нейтральные тона, только самое необходимое",
    promptFragment: "minimalist style, clean lines, neutral colors, uncluttered space",
    previewImage: "https://images.unsplash.com/photo-1586023492125-27264fee7bef?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "scandinavian",
    slug: "scandinavian",
    displayName: "Скандинавский",
    emoji: "🌲",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Светлые тона, натуральное дерево, функциональность",
    promptFragment: "Scandinavian style, light wood, white walls, cozy textiles, functional furniture",
    previewImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "japandi",
    slug: "japandi",
    displayName: "Japandi",
    emoji: "🍃",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Гибрид японской и скандинавской эстетики",
    promptFragment: "Japandi style, wabi-sabi, natural materials, muted tones, Zen simplicity",
    previewImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "organic_modern",
    slug: "organic_modern",
    displayName: "Organic Modern",
    emoji: "🌱",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Натуральные материалы, тёплые оттенки и природная эстетика",
    promptFragment: "organic modern style, natural materials, warm earth tones, curved forms, biophilic",
    previewImage: "https://images.unsplash.com/photo-1586023492125-27264fee7bef?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "contemporary",
    slug: "contemporary",
    displayName: "Contemporary",
    emoji: "🏙️",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Актуальный интерьер с чистыми линиями и функциональностью",
    promptFragment: "contemporary style, clean lines, neutral palette, functional and modern",
    previewImage: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "mid_century",
    slug: "mid_century",
    displayName: "Mid-Century",
    emoji: "🪑",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Стиль 50–60-х с деревянной мебелью и геометрией",
    promptFragment: "mid-century modern style, 1950s wood furniture, geometric forms, retro palette",
    previewImage: "https://images.unsplash.com/photo-1556912167-f556f1f39faa?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "boho",
    slug: "boho",
    displayName: "Boho",
    emoji: "🪷",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Текстиль, растения, этнические элементы и творческая свобода",
    promptFragment: "bohemian style, layered textiles, eclectic decor, warm earthy tones, plants",
    previewImage: "https://images.unsplash.com/photo-1617096200347-cb04ae810b1d?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "coastal",
    slug: "coastal",
    displayName: "Coastal",
    emoji: "🌊",
    category: INTERIOR_STYLE_CATEGORIES.POPULAR,
    description: "Светлый прибрежный интерьер в морской цветовой гамме",
    promptFragment: "coastal style, light blues and whites, natural textures, airy beach atmosphere",
    previewImage: "https://images.unsplash.com/photo-1600210492493-0fd9b353b6e4?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },

  // --- premium ---
  {
    id: "luxury",
    slug: "luxury",
    displayName: "Luxury",
    emoji: "✨",
    category: INTERIOR_STYLE_CATEGORIES.PREMIUM,
    description: "Богатые материалы, золотые акценты, изысканный декор",
    promptFragment: "luxury style, premium materials, gold accents, rich textures, sophisticated atmosphere",
    previewImage: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "artdeco",
    slug: "artdeco",
    displayName: "Art Deco",
    emoji: "🔶",
    category: INTERIOR_STYLE_CATEGORIES.PREMIUM,
    description: "Геометрические узоры, металлический блеск, роскошь",
    promptFragment: "Art Deco style, geometric patterns, bold colors, metallic finishes, glamorous 1930s",
    previewImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "neoclassical",
    slug: "neoclassical",
    displayName: "Neoclassical",
    emoji: "🏛️",
    category: INTERIOR_STYLE_CATEGORIES.PREMIUM,
    description: "Современная интерпретация классического роскошного интерьера",
    promptFragment: "neoclassical style, elegant columns, symmetry, marble, refined luxury",
    previewImage: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },

  // --- nature ---
  {
    id: "biophilic",
    slug: "biophilic",
    displayName: "Biophilic",
    emoji: "🌿",
    category: INTERIOR_STYLE_CATEGORIES.NATURE,
    description: "Живые растения, природные материалы, связь с природой",
    promptFragment: "biophilic style, abundant plants, rattan, wood, natural light, living walls",
    previewImage: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "mediterranean",
    slug: "mediterranean",
    displayName: "Mediterranean",
    emoji: "🌅",
    category: INTERIOR_STYLE_CATEGORIES.NATURE,
    description: "Тёплые тона, терракота, средиземноморский уют",
    promptFragment: "Mediterranean style, warm terracotta, arched niches, mosaic tiles, natural light",
    previewImage: "https://images.unsplash.com/photo-1600210492493-0fd9b353b6e4?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "wabi_sabi",
    slug: "wabi_sabi",
    displayName: "Wabi-Sabi",
    emoji: "🍵",
    category: INTERIOR_STYLE_CATEGORIES.NATURE,
    description: "Японская эстетика естественности и несовершенства",
    promptFragment: "wabi-sabi style, natural imperfection, earthy ceramics, raw textures, muted tones",
    previewImage: "https://images.unsplash.com/photo-1580655653885-65763b2597d0?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "modern_farmhouse",
    slug: "modern_farmhouse",
    displayName: "Modern Farmhouse",
    emoji: "🌾",
    category: INTERIOR_STYLE_CATEGORIES.NATURE,
    description: "Уютный деревенский стиль с натуральными материалами",
    promptFragment: "modern farmhouse style, shiplap walls, natural wood, rustic charm",
    previewImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },

  // --- trendy ---
  {
    id: "loft",
    slug: "loft",
    displayName: "Loft",
    emoji: "🏭",
    category: INTERIOR_STYLE_CATEGORIES.TRENDY,
    description: "Открытые кирпич и бетон, высокие потолки, raw-эстетика",
    promptFragment: "loft style, exposed brick walls, metal pipes, Edison bulbs, open space",
    previewImage: "https://images.unsplash.com/photo-1505409859467-3a796fd5798e?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "cyberpunk",
    slug: "cyberpunk",
    displayName: "Киберпанк",
    emoji: "🌆",
    category: INTERIOR_STYLE_CATEGORIES.TRENDY,
    description: "Неон, тёмные поверхности, футуристичный стиль",
    promptFragment: "cyberpunk style, neon lights, dark atmosphere, high-tech elements, futuristic city",
    // NOTE: no previewImage in legacy STYLE_DISPLAY either — ported as-is.
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "maximalism",
    slug: "maximalism",
    displayName: "Maximalism",
    emoji: "🎭",
    category: INTERIOR_STYLE_CATEGORIES.TRENDY,
    description: "Яркие цвета, насыщенный декор и выразительные акценты",
    promptFragment: "maximalism style, bold colors, rich patterns, layered decor, expressive",
    previewImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "industrial",
    slug: "industrial",
    displayName: "Industrial",
    emoji: "⚙️",
    category: INTERIOR_STYLE_CATEGORIES.TRENDY,
    description: "Металл, бетон, кирпич и индустриальная эстетика",
    promptFragment: "industrial style, exposed brick, metal pipes, concrete floors, Edison bulbs",
    previewImage: "https://images.unsplash.com/photo-1505409859467-3a796fd5798e?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
  {
    id: "japanese_zen",
    slug: "japanese_zen",
    displayName: "Japanese Zen",
    emoji: "🎋",
    category: INTERIOR_STYLE_CATEGORIES.TRENDY,
    description: "Спокойный минималистичный интерьер для медитации",
    promptFragment: "Japanese Zen style, minimalist meditation space, tatami, natural wood, serenity",
    previewImage: "https://images.unsplash.com/photo-1540574163026-643ea20abb28?w=360&q=80&auto=format&fit=crop",
    colors: [],
    materials: [],
    furniture: [],
    lighting: [],
    decor: [],
    negatives: [],
    tags: [],
  },
];
